/**
 * Auditable actions. Every security-relevant state change in the platform is
 * recorded with one of these action names so the activity log is queryable and
 * stable across releases.
 */
export const AuditAction = {
  USER_REGISTERED: 'user.registered',
  USER_GUEST_CREATED: 'user.guest_created',
  USER_DEVICE_OWNER_CREATED: 'user.device_owner_created',
  USER_LOGIN: 'user.login',
  USER_LOGIN_FAILED: 'user.login_failed',
  USER_LOGOUT: 'user.logout',
  USER_PASSWORD_CHANGED: 'user.password_changed',
  USER_PASSWORD_RESET_REQUESTED: 'user.password_reset_requested',
  USER_PASSWORD_RESET_COMPLETED: 'user.password_reset_completed',
  USER_EMAIL_VERIFIED: 'user.email_verified',
  USER_2FA_ENABLED: 'user.two_factor_enabled',
  USER_2FA_DISABLED: 'user.two_factor_disabled',
  AUTH_SESSION_REVOKED: 'auth.session_revoked',
  AUTH_TOKEN_REUSE_DETECTED: 'auth.token_reuse_detected',
  // The one entry that survives a "clear activity" - see DELETE /api/v1/audit.
  ACTIVITY_LOG_CLEARED: 'activity.log_cleared',

  DEVICE_CREATED: 'device.created',
  DEVICE_ENROLLED: 'device.enrolled',
  DEVICE_RENAMED: 'device.renamed',
  DEVICE_REMOVED: 'device.removed',
  DEVICE_ONLINE: 'device.online',
  DEVICE_OFFLINE: 'device.offline',
  DEVICE_PERMISSIONS_UPDATED: 'device.permissions_updated',
  DEVICE_UNATTENDED_ENABLED: 'device.unattended_enabled',
  DEVICE_UNATTENDED_DISABLED: 'device.unattended_disabled',
  DEVICE_UNATTENDED_PASSWORD_SET: 'device.unattended_password_set',
  DEVICE_INCOMING_REQUESTS_ENABLED: 'device.incoming_requests_enabled',
  DEVICE_INCOMING_REQUESTS_DISABLED: 'device.incoming_requests_disabled',
  DEVICE_ACCESS_REVOKED: 'device.access_revoked',
  DEVICE_ENROLLMENT_CODE_ISSUED: 'device.enrollment_code_issued',

  SESSION_REQUESTED: 'session.requested',
  SESSION_STARTED: 'session.started',
  SESSION_DENIED: 'session.denied',
  SESSION_ENDED: 'session.ended',
  SESSION_FAILED: 'session.failed',
  SESSION_TERMINATED_LOCALLY: 'session.terminated_locally',
  SESSION_UNATTENDED_PASSWORD_ACCEPTED: 'session.unattended_password_accepted',
  SESSION_UNATTENDED_PASSWORD_REJECTED: 'session.unattended_password_rejected',
  SESSION_UNATTENDED_PASSWORD_LOCKED: 'session.unattended_password_locked',

  CAPABILITY_REQUESTED: 'capability.requested',
  CAPABILITY_GRANTED: 'capability.granted',
  CAPABILITY_DENIED: 'capability.denied',
  CAPABILITY_STOPPED: 'capability.stopped',

  FILE_UPLOAD_STARTED: 'file.upload_started',
  FILE_UPLOAD_COMPLETED: 'file.upload_completed',
  FILE_DOWNLOAD_STARTED: 'file.download_started',
  FILE_DOWNLOAD_COMPLETED: 'file.download_completed',
  FILE_TRANSFER_FAILED: 'file.transfer_failed',
  FILE_PATH_REJECTED: 'file.path_rejected',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

/** Human-readable label for the activity feed. */
export const AUDIT_LABELS: Record<string, string> = {
  'user.registered': 'Account created',
  'user.guest_created': 'Guest connection started',
  'user.device_owner_created': 'Device self-registered (no account)',
  'user.login': 'Signed in',
  'user.login_failed': 'Failed sign-in attempt',
  'user.logout': 'Signed out',
  'user.password_changed': 'Password changed',
  'user.password_reset_requested': 'Password reset requested',
  'user.password_reset_completed': 'Password reset completed',
  'user.email_verified': 'Email address verified',
  'user.two_factor_enabled': 'Two-factor authentication enabled',
  'user.two_factor_disabled': 'Two-factor authentication disabled',
  'auth.session_revoked': 'Sign-in session revoked',
  'auth.token_reuse_detected': 'Refresh token reuse detected',
  'activity.log_cleared': 'Activity log cleared',
  'device.created': 'Device added',
  'device.enrolled': 'Agent enrolled',
  'device.renamed': 'Device renamed',
  'device.removed': 'Device removed',
  'device.online': 'Device came online',
  'device.offline': 'Device went offline',
  'device.permissions_updated': 'Device permissions updated',
  'device.unattended_enabled': 'Unattended access enabled',
  'device.unattended_disabled': 'Unattended access disabled',
  'device.incoming_requests_enabled': 'Connection requests allowed',
  'device.incoming_requests_disabled': 'Connection requests blocked',
  'device.unattended_password_set': 'Unattended access password set',
  'device.access_revoked': 'Device access revoked',
  'device.enrollment_code_issued': 'Enrollment code issued',
  'session.requested': 'Remote session requested',
  'session.started': 'Remote session started',
  'session.denied': 'Remote session declined',
  'session.ended': 'Remote session ended',
  'session.failed': 'Remote session failed',
  'session.terminated_locally': 'Session ended at the remote computer',
  'session.unattended_password_accepted': 'Connected using the unattended access password',
  'session.unattended_password_rejected': 'Incorrect unattended access password',
  'session.unattended_password_locked': 'Unattended access temporarily locked after repeated failed attempts',
  'capability.requested': 'Capability requested',
  'capability.granted': 'Capability granted',
  'capability.denied': 'Capability denied',
  'capability.stopped': 'Capability stopped',
  'file.upload_started': 'File upload started',
  'file.upload_completed': 'File upload completed',
  'file.download_started': 'File download started',
  'file.download_completed': 'File download completed',
  'file.transfer_failed': 'File transfer failed',
  'file.path_rejected': 'Blocked access to a path outside shared folders',
};
